### PR TITLE
RIA-3542: Support for parallel browser runs when cucumbertags provided.

### PR DESCRIPTION
**Pull request by rohithtiru**
This change uses getMultiCapabilities instead of capabilities
  configuration of protractor when the options --parallel-scenarios
  or --parallel-features is provided. To control the number of
  browsers, the environment variable 'PARALLEL_BROWSERS_COUNT'
  can be used.

  Examples:
    PARALLEL_BROWSERS_COUNT=2 TEST_E2E_HEADLESS=false yarn e2e --parallel-scenarios --cucumberOpts.tags=@nightly-test
    PARALLEL_BROWSERS_COUNT=2 TEST_E2E_HEADLESS=false yarn e2e --parallel-features --cucumberOpts.tags="@nightly-test or @submit-appeal"

**Before creating a pull request make sure that:**

- [ x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-3542

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Comment by rohith-tiru** [comment]
**rohith@rohith-home-work:~/workspaces/solirius/repos/ia-ccd-e2e-tests$ PARALLEL_BROWSERS_COUNT=2 TEST_E2E_HEADLESS=false yarn run localTestParallelFeatures "--cucumberOpts.tags=@share-a-case or @RIA-585"**
yarn run v1.22.4
$ protractor ./e2e/features.parallel.conf.js --parallel-features --cucumberOpts.tags=~@toggled-off --cucumberOpts.tags=~@OnlyIfSaveAndContinueIsEnabled --cucumberOpts.format='node_modules/cucumber-pretty' '--cucumberOpts.tags=@share-a-case or @RIA-585'
cucumber opts tags : ~@toggled-off,~@OnlyIfSaveAndContinueIsEnabled,@share-a-case or @RIA-585
List of tests to run : {
  "features": [
    "e2e/features/share-a-case.feature",
    "e2e/features/start-appeal-nationalities.feature"
  ],
  "scenarios": []
}
[15:52:23] I/launcher - Running 2 instances of WebDriver
...[15:52:41] I/testLogger - 
------------------------------------

[15:52:41] I/testLogger - [chrome #11] PID: 204826
[chrome #11] Specs: /home/rohith/workspaces/solirius/repos/ia-ccd-e2e-tests/e2e/features/start-appeal-nationalities.feature
[chrome #11] 
[chrome #11] [15:52:24] I/direct - Using ChromeDriver directly...
[chrome #11] Feature: Nationalities
[chrome #11] 
[chrome #11]   @regression @start-appeal @alternate @RIA-585 @migrate-to-unit-tests
[chrome #11]   Scenario: The Nationalities list contains all ISO countries
[chrome #11]     Given I am signed in as a `Legal Rep`
[chrome #11]     And I create a new case
[chrome #11]     And I complete the `Tell us about your client` page
[chrome #11]     And I complete the `Home office details` page
[chrome #11]     And I complete the `Upload the Notice of Decision` page
[chrome #11]     Given I am on the `Basic details` page
[chrome #11]     When I add an item to the `Nationality` collection
[chrome #11]     Then I see a list of all nationalities
[chrome #11] 
[chrome #11] 1 scenario (1 passed)
[chrome #11] 8 steps (8 passed)
[chrome #11] 0m15.934s

[15:52:41] I/testLogger - 

[15:52:41] I/launcher - 1 instance(s) of WebDriver still running
....................[15:53:19] I/testLogger - 
------------------------------------

[15:53:19] I/testLogger - [chrome #01] PID: 204816
[chrome #01] Specs: /home/rohith/workspaces/solirius/repos/ia-ccd-e2e-tests/e2e/features/share-a-case.feature
[chrome #01] 
[chrome #01] [15:52:24] I/direct - Using ChromeDriver directly...
[chrome #01] Feature: Share a case
[chrome #01] 
[chrome #01]   @regression @share-a-case @happy-path
[chrome #01]   Scenario: Share a case with another user
[chrome #01]     Given I am signed in as a `Legal Org User Rep A`
[chrome #01]     And I create a new case
[chrome #01]     And I save my initial appeal
[chrome #01]     And I submit my appeal
[chrome #01]     When I click the `Overview` tab
[chrome #01]     And I select the `Share case with colleague` Next step
[chrome #01]     And I wait for Share case page to load
[chrome #01]     And I choose `Legal Org User Rep B`
[chrome #01]     And I complete the `Share a case check your answers` page
[chrome #01]     When I switch to be a `Legal Org User Rep B`
[chrome #01]     When I click the `Overview` tab
[chrome #01]     And I should see the text `Do this next`
[chrome #01]     And I click the `Appeal` tab
[chrome #01]     And I should see the `Appeal` page
[chrome #01]     And I click the `Appellant` tab
[chrome #01]     And I should not see any case progress images
[chrome #01]     And I should see the appellant's details
[chrome #01]     And I should not see the decision fields
[chrome #01]     And I click the `Documents` tab
[chrome #01]     Then I should see the `Documents` page
[chrome #01]     And I should see the `Legal representative documents` field
[chrome #01]     And within the `Legal representative documents` collection's first item, I should see `{$TODAY|D MMM YYYY}` for the `Date uploaded` field
[chrome #01]     And I click the `Directions` tab
[chrome #01]     And I should see the `Directions` field
[chrome #01] 
[chrome #01] 1 scenario (1 passed)
[chrome #01] 24 steps (24 passed)
[chrome #01] 0m53.112s

[15:53:19] I/testLogger - 

[15:53:19] I/launcher - 0 instance(s) of WebDriver still running
[15:53:19] I/launcher - chrome #11 passed
[15:53:19] I/launcher - chrome #01 passed
Done in 56.56s.
rohith@rohith-home-work:~/workspaces/solirius/repos/ia-ccd-e2e-tests$ git push -f
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 3.02 KiB | 3.02 MiB/s, done.
Total 7 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com:hmcts/ia-ccd-e2e-tests.git
 + 9008df5...4c03683 RIA-3542-parallel-browser-runs -> RIA-3542-parallel-browser-runs (forced update)
rohith@rohith-home-work:~/workspaces/solirius/repos/ia-ccd-e2e-tests$

**Comment by rohith-tiru** [comment]
**Parallel Scenarios Run : 

rohith@rohith-home-work:~/workspaces/solirius/repos/ia-ccd-e2e-tests$ PARALLEL_BROWSERS_COUNT=2 TEST_E2E_HEADLESS=false yarn run localTestParallelScenarios "--cucumberOpts.tags=@share-a-case or @RIA-585"**
yarn run v1.22.4
$ protractor ./e2e/features.parallel.conf.js --parallel-scenarios --cucumberOpts.tags=~@toggled-off --cucumberOpts.tags=~@OnlyIfSaveAndContinueIsEnabled --cucumberOpts.format='node_modules/cucumber-pretty' '--cucumberOpts.tags=@share-a-case or @RIA-585'
cucumber opts tags : ~@toggled-off,~@OnlyIfSaveAndContinueIsEnabled,@share-a-case or @RIA-585
List of tests to run : {
  "features": [],
  "scenarios": [
    "e2e/features/share-a-case.feature:9",
    "e2e/features/start-appeal-nationalities.feature:11"
  ]
}
[16:03:12] I/launcher - Running 2 instances of WebDriver
...[16:03:31] I/testLogger - 
------------------------------------

[16:03:31] I/testLogger - [chrome #11] PID: 209820
[chrome #11] Specs: /home/rohith/workspaces/solirius/repos/ia-ccd-e2e-tests/e2e/features/start-appeal-nationalities.feature:11
[chrome #11] 
[chrome #11] [16:03:13] I/direct - Using ChromeDriver directly...
[chrome #11] Feature: Nationalities
[chrome #11] 
[chrome #11]   @regression @start-appeal @alternate @RIA-585 @migrate-to-unit-tests
[chrome #11]   Scenario: The Nationalities list contains all ISO countries
[chrome #11]     Given I am signed in as a `Legal Rep`
[chrome #11]     And I create a new case
[chrome #11]     And I complete the `Tell us about your client` page
[chrome #11]     And I complete the `Home office details` page
[chrome #11]     And I complete the `Upload the Notice of Decision` page
[chrome #11]     Given I am on the `Basic details` page
[chrome #11]     When I add an item to the `Nationality` collection
[chrome #11]     Then I see a list of all nationalities
[chrome #11] 
[chrome #11] 1 scenario (1 passed)
[chrome #11] 8 steps (8 passed)
[chrome #11] 0m16.464s

[16:03:31] I/testLogger - 

[16:03:31] I/launcher - 1 instance(s) of WebDriver still running
....................[16:04:11] I/testLogger - 
------------------------------------

[16:04:11] I/testLogger - [chrome #01] PID: 209819
[chrome #01] Specs: /home/rohith/workspaces/solirius/repos/ia-ccd-e2e-tests/e2e/features/share-a-case.feature:9
[chrome #01] 
[chrome #01] [16:03:13] I/direct - Using ChromeDriver directly...
[chrome #01] Feature: Share a case
[chrome #01] 
[chrome #01]   @regression @share-a-case @happy-path
[chrome #01]   Scenario: Share a case with another user
[chrome #01]     Given I am signed in as a `Legal Org User Rep A`
[chrome #01]     And I create a new case
[chrome #01]     And I save my initial appeal
[chrome #01]     And I submit my appeal
[chrome #01]     When I click the `Overview` tab
[chrome #01]     And I select the `Share case with colleague` Next step
[chrome #01]     And I wait for Share case page to load
[chrome #01]     And I choose `Legal Org User Rep B`
[chrome #01]     And I complete the `Share a case check your answers` page
[chrome #01]     When I switch to be a `Legal Org User Rep B`
[chrome #01]     When I click the `Overview` tab
[chrome #01]     And I should see the text `Do this next`
[chrome #01]     And I click the `Appeal` tab
[chrome #01]     And I should see the `Appeal` page
[chrome #01]     And I click the `Appellant` tab
[chrome #01]     And I should not see any case progress images
[chrome #01]     And I should see the appellant's details
[chrome #01]     And I should not see the decision fields
[chrome #01]     And I click the `Documents` tab
[chrome #01]     Then I should see the `Documents` page
[chrome #01]     And I should see the `Legal representative documents` field
[chrome #01]     And within the `Legal representative documents` collection's first item, I should see `{$TODAY|D MMM YYYY}` for the `Date uploaded` field
[chrome #01]     And I click the `Directions` tab
[chrome #01]     And I should see the `Directions` field
[chrome #01] 
[chrome #01] 1 scenario (1 passed)
[chrome #01] 24 steps (24 passed)
[chrome #01] 0m56.294s

[16:04:11] I/testLogger - 

[16:04:11] I/launcher - 0 instance(s) of WebDriver still running
[16:04:11] I/launcher - chrome #11 passed
[16:04:11] I/launcher - chrome #01 passed
Done in 59.73s.

**Review by bradsorour — DISMISSED** [review]
LGTM

**Comment by rohith-tiru** [comment]
There was a Typo in README.md which i have changed as part of the fixup commit.

**Review by burale — APPROVED** [review]
LGTM

**Pull request merged**
